### ISSUE TITLE
User data?

### ISSUE THREAD

**Issue by al786999** [unblocked/ec2-action-builder#43]
For our spot instances we would need terraform and AWS cli  installed - how do we do it with this action? Can we leverage user data somehow or other commands ? Also does this action need a GitHub based runner or dedicated “listening” runner to trigger the spot instances ?

**Comment by mahdi-torabi** [comment]
For installing dependencies you could either do it as part of the job:
```yaml
  jobs:
    start-runner:
        timeout-minutes: 5              # normally it only takes 1-2 minutes
        name: Start self-hosted EC2 runner   
        runs-on: ubuntu-latest
        permissions:
          actions: write        
        steps:      
          - name: Start EC2 runner
            id: start-ec2-runner
            uses: NextChapterSoftware/ec2-action-builder@v1.10
            with:
              github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
              aws_access_key_id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
              aws_secret_access_key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
              aws_region: "us-west-2"
              ec2_instance_type: c5.4xlarge
              ec2_ami_id: ami-008fe2fc65df48dac
              ec2_iam_instance_profile: AWSInstanceProfile
              ec2_subnet_id: "SUBNET_ID_REDACTED"
              ec2_security_group_id: "SECURITY_GROUP_ID_REDACTED"
              ec2_instance_ttl: 40                # Optional (default is 60 minutes)
              ec2_spot_instance_strategy: None    # Other options are: SpotOnly, BestEffort, MaxPerformance 

    # Job that runs on the self-hosted runner 
    run-build:
        timeout-minutes: 1
        needs:
          - start-runner
        runs-on: ${{ github.run_id }}          
        steps:              
          - name: Install AWS CLI
            run: |
              sudo apt-get update && sudo apt-get install -y unzip curl
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install --update
```

Or prepare an EC2 AMI with your tooling installed and configured then use that AMI for launching the runners by passing it as `ec2_ami_id`. 


As for your second question, We need a GH runner for the initial setup which provisions the spot instance. Once the spot instance is up then the second stage runs on the EC2. So yes it does need a GH runner to run this action and provision resources.
